# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NYSGeocoder
                                 A QGIS plugin
 Geocode street addresses in New York State
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-03
        copyright            : (C) 2019 by Keith Jenkins
        email                : kgj2@cornell.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NYSGeocoder class from file NYSGeocoder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .nys_geocoder import NYSGeocoder
    return NYSGeocoder(iface)
